### PR TITLE
Docs configurations

### PR DESCRIPTION
**Pull request by rafaelbernard**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build:check` or `yarn build:check`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint` or `yarn lint`) has passed locally and any fixes were made for failures

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Documentation providing information about audit parameters and their default values.

I will provide another documentation for plugins configuration.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by grgur** [comment]
thanks for doing this @rafaelbernard

**Comment by mitchellsimoens** [comment]
@rafaelbernard looking good to me

**Comment by rafaelbernard** [comment]
I will provide another documentation for plugins configuration.

**Comment by grgur** [comment]
@rafaelbernard Thank you for your contributions so far. You are definitely lowering the barrier to entry, which is now one of the most important things Gimbal needs.

Would you like to continue working on this PR?

**Comment by rafaelbernard** [comment]
@grgur Yes, I would like to keep contributing. I think this PR is finished. Do you think that I missed anything?

**Pull request merged**
